Roll src/third_party/dart 5244d99a5d4e..5fc031ebc1d7 (42 commits)
https://dart.googlesource.com/sdk.git/+log/5244d99a5d4e..5fc031ebc1d7

git log 5244d99a5d4e..5fc031ebc1d7 --date=short --first-parent --format='%ad %ae %s'
2020-02-11 asiva@google.com [VM/Libraries] Turn on NNBD versions of dart:io and dart:_http libraries
2020-02-11 nshahan@google.com Remove import of dart:mirrors from dart:html
2020-02-11 scheglov@google.com Issue 40572. Pass Packages to AnalysisDriver.
2020-02-11 srujzs@google.com Fix input and output for conversions
2020-02-10 bkonyi@google.com Reland "[ DartFuzz ] Prevent generated programs from explicitly throwing OutOfMemoryError"
2020-02-10 pquitslund@google.com driver test suggestion support
2020-02-10 scheglov@google.com Issue 40482. Fix for Function?.call() reporting unchecked nullable.
2020-02-10 alexmarkov@google.com [vm/nnbd] Fix lazy _InvocationMirror._type initialization
2020-02-10 scheglov@google.com Issue 40398. Fix for checking type arguments in legacy libraries.
2020-02-10 scheglov@google.com Issue 40414. Test for invalid override checked even via legacy library.
2020-02-10 devoncarew@google.com [nnbd preview] update item presentation; show line numbers
2020-02-10 stuartmorgan@google.com Fix issues found compiling with clang on Windows
2020-02-10 srujzs@google.com Handle optionals in DOM scripts for NNBD
2020-02-10 zichangguo@google.com Reland "fix hanging of write on Windows"
2020-02-10 scheglov@google.com Optional parameters of abstract methods may omit default values.
2020-02-10 nbosch@google.com Simplify analyzer pub constraints
2020-02-10 jcollins@google.com Fix windows bot failure due to missing path conversion.
2020-02-10 rmacnak@google.com [vm] Further mirrors and test fixes.
2020-02-10 paulberry@google.com Migration: Allow null info when introducing `as`.
2020-02-10 paulberry@google.com Migration: fix hard crash in trial_migration when migrating package:async.
2020-02-10 rmacnak@google.com [vm] Never enter a safepoint under a regular MutexLocker.
2020-02-10 regis@google.com [VM/nnbd] Update runtime and code generation of 'is instance of' for NNBD.
2020-02-10 rnystrom@google.com Bump the version numbers in the test package config to "2.7".
2020-02-10 srujzs@google.com Add null-safety to html_common
2020-02-10 pquitslund@google.com migrate path specification to driver clients
2020-02-10 srujzs@google.com Don't generate getters/setters for read only promises
2020-02-10 markzipan@google.com [dartdevc] Wrapping function types with nullability wrappers.
2020-02-10 scheglov@google.com Issue 40546. Ensure that getSourceKind() works for changed files.
2020-02-10 liama@google.com [lib] Re-add a null check in Double.toStringAsPrecision
2020-02-10 liama@google.com [lib] Fix some NNBD lib tests
2020-02-10 alexmarkov@google.com [vm/nnbd] Fix RangeError in NoSuchMethodError._toStringDeprecated
2020-02-10 markzipan@google.com [dartdevc] Implementing generic function type object equality.
2020-02-10 markzipan@google.com [dartdevc] Adding support for required named parameters weak mode semantics.
2020-02-10 pquitslund@google.com completion driver suggestions
2020-02-10 dacoharkes@google.com [vm/ffi] Fix sign extension for small int arguments on x64 Linux/MacOS
2020-02-10 kustermann@google.com [vm/concurrency] Ensure TFA doesn't eliminate static field, to ensure objects stay alive when asking for allocation stats
2020-02-10 rnystrom@google.com Create a package_config.json file for the generated multitests.
2020-02-10 sstrickl@google.com Reland "[vm/aot] Remove object wrapping of bare instructions for AOT snapshots."
2020-02-10 askesc@google.com Revert "[VM/Libraries] Turn on NNBD versions of dart:io and dart:_http libraries"
2020-02-10 dacoharkes@google.com [vm/ffi] NNBD: Change nullptr type argument to Never
2020-02-10 eernst@google.com Ensuring that every feature spec in SDK is marked as background material
2020-02-09 brianwilkerson@google.com Improve some diagnostic documentation

Created with:
  gclient setdep -r src/third_party/dart@5fc031ebc1d7

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/dart-sdk-flutter-engine
Please CC dart-vm-team@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+/master/autoroll/README.md

Bug: None
Tbr: dart-vm-team@google.com