Roll Skia from e2c9d3c034dc to ec04e062f3f5 (5 revisions)
https://skia.googlesource.com/skia.git/+log/e2c9d3c034dc..ec04e062f3f5

2021-02-10 bsalomon@google.com Drop AA on quads that are extremely thin before AA insetting/outsetting.
2021-02-10 stani@google.com Android roll broke with a compilation error: frameworks/base/libs/hwui/jni/Shader.cpp:243:37: error: no matching function for call to 'get'     sk_sp<SkRuntimeEffect> effect = std::get<0>(result)
2021-02-09 michaelludwig@google.com Delete deprecated alpha threshold header
2021-02-09 johnstiles@google.com Add support for matrix == and != in Metal shaders.
2021-02-09 jvanverth@google.com Implement indirect draws in Metal

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/skia-flutter-autoroll
Please CC borenet@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md