maybeGetInitialRouteFromIntent: check if URI data getPath() is null
https://developer.android.com/reference/android/net/Uri?hl=da#getPath()
getPath returns a null in case of non-hierachical URIs like mailto

This avoids the app crashing with:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference