Revert "Enable Skia's Vulkan backend on all non-mobile platforms, and test SwiftShader Vulkan on all GL unittests platforms (#29520)"
Causes the following build breakage (Win32):

    [19/1564] CXX obj/flutter/vulkan/vulkan.vulkan_window.obj
    FAILED: obj/flutter/vulkan/vulkan.vulkan_window.obj
    ninja -t msvc -e environment.x64 --
    ../../buildtools/windows-x64/clang/bin/clang-cl.exe  /nologo
    /showIncludes @obj/flutter/vulkan/vulkan.vulkan_window.obj.rsp /c
    ../../flutter/vulkan/vulkan_window.cc
     /Foobj/flutter/vulkan/vulkan.vulkan_window.obj
     /Fdobj/flutter/vulkan/vulkan_cc.pdb
     ../../flutter/vulkan/vulkan_window.cc(125,24): error: no member named
     'MakeVulkan' in 'GrDirectContext'
           GrDirectContext::MakeVulkan(backend_context, options);
                 ~~~~~~~~~~~~~~~~~^
                 1 error generated.

This reverts commit bba38c0b83122ec9b174271e74499d739416208b.