Add workaround for missing fl_method_xxx_response_get_type() symbols
Using the following macros:

- FL_METHOD_SUCCESS_RESPONSE()
- FL_METHOD_ERROR_RESPONSE()
- FL_METHOD_NOT_IMPLEMENTED_RESPONSE()

Would result to linking errors:

    /usr/bin/ld: foo_plugin.so: undefined reference to `fl_method_success_response_get_type'
    /usr/bin/ld: foo_plugin.so: undefined reference to `fl_method_error_response_get_type'
    /usr/bin/ld: foo_plugin.so: undefined reference to `fl_method_not_implemented_response_get_type'

See also commit 6e378cf.