Add missing import
Fixes the following:

https://github.com/flutter/engine/commit/6b262a0529bea8c58eb763fe15bd8d647dd07641 results in the following error appearing internally when compiling for Android:

```
In file included from fml/synchronization/sync_switch.cc:5:
./fml/synchronization/sync_switch.h:74:34: error: implicit instantiation of undefined template 'std::vector<fml::SyncSwitch::Observer *>'
  mutable std::vector<Observer*> observers_;
                                 ^
<...>: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
1 error generated.
```