Roll src/third_party/dart 1f1592edce..e70273c306 (78 commits)
e70273c306 Issue 36733. Completion in spread, if, and for elements.
d0b236c319 [dart/fuzzer] restrict stmt depth and length
ccf7eac86d [vm, jit] Make unoptimized instance calls compatible with megamorphic calls.
bba0be2797 Rework type parameters, use correct enclosing element / reference.
317a075d93 [vm] Fix DEGUG typo and a few other bugs it was hiding.
05d33b1240 Add WorkspacePackage support for InSummarySource sources
eeb7a92b21 Pass the authentication code when fetching timeline and CPU profile data
76c6b86915 Revert "[Infra] Let run_vm_tests --list output a test expectation marker"
9238e25305 Revert "[vm] Finish adding support for ECMAScript 2018 features."
000a3eb3f7 Add completion support for late and required
4da31564cb Fix the placement of late in two tests
7cb73d97d2 [Infra] Let run_vm_tests --list output a test expectation marker
a3c19d4ffc [vm/compiler] Move inlining/intrinsics pipeline passes to compiler_pass.h
5fc8029587 Remove StaticMemberUsage and cleanup codegen world builder
a0a51a7cde Resynthesize fields.
3fd6fa4ff7 [vm] Fix errors compiling with GCC.
225516466f [vm, interpreter] noSuchMethod dispatchers as a bytecode.
f3bd910e10 Only use MapFormatter for SDK maps (HashMap and LinkedHashMap)
f82000dfb1 pre-nnbd modifier as identifier tests
f3e86852de Fix the order of arguments when composing an error message (issue 36732)
f04cac8fbd Implement inheritsCovariant.
2cadc90ec5 Add summary support for isLate
a28d5e7a0f Rework reportTypeErrorForNode() to work even when FunctionType does not have an element.
f7c67ee927 [dart/vm] Use EvenSRegisterOf() instead of unclear cast
e7175ac2ed [vm, fuchsia] Consume specialized symbols for the Dart VM's profiler.
91e9962699 Don't report libraries that became parts as changed libraries.
ec09fab85a Create elements for @prefix in LInkedElementFactory.
2c77aae6b3 Support for LibraryElementImpl.hasExtUri
e6260f67b3 [dart/fuzzer] Remove hashCode from API table
c3e7859035 Store raw elements for parameters.
e429cba1ec [vm] Change FpuTMP to XMM15/XMM7 on X64/IA32.
9a03c94d36 Clean up ParseBase's use of AnalysisOptions.experimentStatus
0c5199d467 Wrapper script for running ABI tests
c5e57cc078 Plumb FeatureSet through resolver
296505e2e3 Sort declarations in pkg/analyzer/test/generated/parser_test.dart
ed984b6985 Sort declarations in pkg/analyzer/test/dart/ast/ast_test.dart
8516ad8256 Sort declarations in pkg/analyzer/lib/src/dart/sdk/sdk.dart
efd1ccb31a Modify the MOVE_FILE refactoring support to be passed a resolved unit like other refactorings.
43e26c2de9 Add highlight support for late and required
e42c5d12fe Cleanup tests by removing references to enabled experiments and by reducing duplication
663919e361 [vm] Free error if embedder failed to start service isolate
650cd2ed1d [gardening] Fix multitest comments on this file.
5ebb640a67 [vm] Finish adding support for ECMAScript 2018 features.
c4ab0d2014 Inline create methods in JsKernelToElementMap
446c6754d6 Fix runtime type error in Swarm
db8f0090a5 Separate mixins into @mixin, build GenericTypeAlias.
d6a09ff02f Prepare to publish analyzer version 0.36.2
07017d33a6 pkg/analyzer_plugin: support the latest pkg:analyzer
9af0574287 Remove unused import
2eb36e8879 [dart/vm] What's in a (register) name?
b5769936a9 Perform mixin inference during types building.
d06121ea89 [vm/compiler] Remove AbortBackgroundCompilation from guard instructions
4624419736 Support UI-as-code in deprecated parse functions.
ca9bbd39d5 [dartdevc] Remove ddc and ddk pre-compiled "legacy" sdk modules
e695bc3c6d Record type inference errors for fields and parameters.
174395a49e NNBD "late" modifier language_2 tests
7c18fc0c3d Revert "[gardening] Mark ffi/function_stress_test/1 test as slow."
2c4dc7a431 Support targetting flutter and flutter_runner in kernel_worker
2298712d62 [vm] fix position of DebugStepCheck when building break statement in flowgraph
c66a67c4a3 Rename isLazy to isLate to reflect change in keyword
ab7e9500c7 [vm, arm64] Fix some assertions.
b9be35b3fc Perform override and initializer inference at the same time when required.
34f0bed189 Use the correct syntax for null-aware spread in CHANGELOG.
04e1b0d976 [ VM ] Updated standalone VM to display message about --disable-service-auth-codes when --help --verbose is provided.
688f029c4f Rename workspace to refactoringWorkspace in move_file.dart to clarify the type of the object.
7388c3e3db [gardening] Mark ffi/function_stress_test/1 test as slow.
594a0ef7a7 Perform instantiateToBounds() even for not simply bounded types.
b4d17f2eee Add diagnostics related to default values
dbfcb97fa5 [dart/vm]: sometimes a smi is just a smi
cee1e41fe8 Plumb new FeatureSet class into Scanner.
293c0f42f7 NNBD "required" modifier language_2 tests
bb2a3ca6f6 Plumb FeatureSet into ConstantVerifier
81b028de78 cleanup some error codes
80d4b9a5db [vm/frontend_server] Expose protobuf aware tree shaker in frontend server
b7375d0360 Nit: convert singular tab into spaces in test_matrix.json.
a58aa6f705 Fix NoSuchMethodError in observatory when setting breakpoint via debugger console
86fe7ca75c Fix build when python=python3
475c918f0a [infra] Run analyzer unit tests only on analyzer builders