Roll src/third_party/dart 617bc54b715d..b2e300bb7b90 (25 commits)
https://dart.googlesource.com/sdk.git/+log/617bc54b715d..b2e300bb7b90

git log 617bc54b715d..b2e300bb7b90 --date=short --first-parent --format='%ad %ae %s'
2020-05-08 aam@google.com [vm/isolates] Fix race in ring_gc_* tests.
2020-05-08 rmacnak@google.com [vm, gc] Rename HeapPage to OldPage for symmetry.
2020-05-08 brianwilkerson@google.com Make createSuggestion an instance method and clean up some code in SuggestionBuilder
2020-05-08 brianwilkerson@google.com Move another batch of fixes to be producers
2020-05-08 regis@google.com [VM/compiler] Emit a throw NoSuchMethodError for bad arity rather than aborting compilation.
2020-05-08 johnniwinther@google.com [cfe] Update id-tests post unfork
2020-05-08 rmacnak@google.com [vm] Fix -Wno-conversion-null errors.
2020-05-08 zra@google.com [dart:io, windwos] Try a shorter temp directory name first
2020-05-08 rmacnak@google.com [vm] Disable thread leak detection in TSAN build.
2020-05-08 devoncarew@google.com [dartdev] update help text
2020-05-08 scheglov@google.com Split computing interface for class and mixin.
2020-05-08 alexmarkov@google.com [vm] Cleanup flags which disable argument type checks and strong mode types
2020-05-08 keertip@google.com Add prefix start information for completions
2020-05-08 brianwilkerson@google.com Convert LocalConstructorContributor to use SuggestionBuilder
2020-05-08 paulberry@google.com Migration: reorganize code in source_edit_diff_formatter.dart
2020-05-08 joshualitt@google.com [dart2js] Re-enable an inference_test.
2020-05-08 paulberry@google.com Migration: sort declarations in instrumentation.dart.
2020-05-08 paulberry@google.com Migration: assign better quality node targets in NodeBuilder.
2020-05-08 joshualitt@google.com [dart2js] Delete generate_code_with_compile_time_errors_test.
2020-05-08 srawlins@google.com analyzer: Do not report non-EOL doc comments in codes.dart
2020-05-08 sigmund@google.com [dart2js] enable null-safety also when deserializating the global data
2020-05-08 scheglov@google.com Fix avoid_unused_constructor_parameters in analyzer.
2020-05-08 sigmund@google.com [dart2js] add testing for prennbd sdk and cleanup nnbd enabled tests.
2020-05-08 asiva@google.com [Tests] Skip valid_source_locations_test for ia32 and simarm* configurations
2020-05-08 aam@google.com [vm/isolates] Skip dart/isolates/ring_gc_* tests.

Created with:
  gclient setdep -r src/third_party/dart@b2e300bb7b90

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/dart-sdk-flutter-engine
Please CC dart-vm-team@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+/master/autoroll/README.md

Bug: None
Tbr: dart-vm-team@google.com